dist: trusty
sudo: required
language: node_js
node_js:
  - node
#  - '12'
cache:
  directories:
    - ./node_modules
addons:
  chrome: stable
services:
  - docker
before_install:
  - docker pull node:12.7-alpine
  - docker build -t si-project-web-app-image .
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - fluxbox >/dev/null 2>&1 &

script:
  - npm run lint
  - docker run --name si-project-web-app-container -d -p 5555:80 si-project-web-app-image
  #- npm run lint
 # - npm run build
#  - docker run --rm si-project-web-app-image npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
before_deploy:
  - pyenv install 3.6
  - pip install -U pip
  - pip install awscli
  # make the script executable
  - chmod +x set_aws_credentials.sh
  # set up temporary aws session credentials, remember to update env. variables
  # in the file set_aws_credentials.sh in travis for every login and refresh on aws
  - ./set_aws_credentials.sh
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "si-project-web-app"
  env: "SiProjectWebApp-env"
  bucket_name: elasticbeanstalk-us-east-1-874110563259
  bucket_path: "si-project-web-app"
#  access_key_id:
#  secret_access_key:
  on:
    branch: issue-21-upload_frontend_to_aws
