language: node_js
dist: trusty

node_js:
  - "12"
sudo: required

env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH
cache:
  directories:
    - ./node_modules

addons:
  chrome: stable

before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - npm run test-headless # ou ng test
  - ng build --prod --base-href https://t-palmer.github.io/travis-demo/ #this can be submitted as environment variable

before_deploy:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli
  # make the script executable
  - chmod +x set_aws_credentials.sh
  # set up temporary aws session credentials, remember to update env. variables
  # in the file set_aws_credentials.sh in travis for every login and refresh on aws
  - ./set_aws_credentials.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: deploy_script.sh
    on:
      branch: issue-21-upload_frontend_to_aws
