language: node_js


dist: trusty

node_js:
  - "12"
sudo: required

env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH
cache:
  directories:
    - ./node_modules

addons:
  chrome: stable

before_script:
  - npm install -g @angular/cli

script:
  #- npm run lint
  #- npm run test
  - ng build  #this can be submitted as environment variable

install:
  - PYENV_VERSION=1.2.20
  - PYTHON_VERSION=3.8.7
  - pushd $(pyenv root)
  - git fetch
  - git checkout v$PYENV_VERSION
  - pyenv install -v ${PYTHON_VERSION}
  - popd
before_deploy:
  - pyenv global $PYTHON_VERSION
  - pip install -U pip
  - pip install awscli
  # make the script executable
  - chmod +x set_aws_credentials.sh
  - chmod +x deploy_script.sh
  # set up temporary aws session credentials, remember to update env. variables
  # in the file set_aws_credentials.sh in travis for every login and refresh on aws
  - ./set_aws_credentials.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: deploy_script.sh
    wait_until_deployed: true
    on:
      branch: issue-21-upload_frontend_to_aws
