dist: trusty
sudo: required
language: node_js
node_js:
  - node
#  - '12'
cache:
  directories:
    - ./node_modules
addons:
  chrome: stable
services:
  - docker
before_install:
  - docker pull node:12.7-alpine
  - docker build -t si-project-web-app-image .
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - fluxbox >/dev/null 2>&1 &

script:
  - docker run --rm si-project-web-app-image npm run lint
  - docker run --name si-project-web-app-container -d -p 5555:80 si-project-web-app-image
  #- npm run lint
 # - npm run build
#  - docker run --rm si-project-web-app-image npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

