language: node_js


dist: trusty

node_js:
  - "12"
sudo: required

env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH
cache:
  directories:
    - ./node_modules

addons:
  chrome: stable

before_script:
  - npm install -g @angular/cli
script:
  #- npm run lint
  #- npm run test
  - ng build  #this can be submitted as environment variable
before_install:
  - choco install python --version 3.8.0
  - python -m pip install --upgrade pip
  env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
before_deploy:
  - pyenv global 3.8.0
  - pip install -U pip
  - pip install awscli
  # make the script executable
  - chmod +x set_aws_credentials.sh
  - chmod +x deploy_script.sh
  # set up temporary aws session credentials, remember to update env. variables
  # in the file set_aws_credentials.sh in travis for every login and refresh on aws
  - ./set_aws_credentials.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: deploy_script.sh
    wait_until_deployed: true
    on:
      branch: issue-21-upload_frontend_to_aws
