dist: trusty
sudo: required
language: node_js
node_js:
  - node
  - '12'

addons:
  chrome: stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - fluxbox >/dev/null 2>&1 &

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run lint
  - npm run build
#  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

